backend:
  name: github
  repo: mahedihasan4/MS-Fashion-Store-
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "প্রোডাক্টসমূহ"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "প্রোডাক্ট আইডি (ID)", name: "id", widget: "number" }
      - { label: "প্রোডাক্টের নাম (Product Name)", name: "name", widget: "string" }
      - { label: "ক্যাটাগরি (Category)", name: "category", widget: "select", options: ["Saree", "Three Piece", "One Piece"] }
      - { label: "মূল্য (Price)", name: "price", widget: "number" }
      - { label: "প্রোডাক্টের বিবরণ (Description)", name: "description", widget: "text" }
      - { label: "ডিটেইলস/স্পেসিফিকেশন (Details)", name: "details", widget: "list", summary: "{{fields.detail}}" }
      - { 
          label: "কালার ভ্যারিয়েন্ট (Colors)", 
          name: "colors", 
          widget: "list", 
          fields: [
            { label: "কালারের নাম", name: "name", widget: "string" },
            { label: "কালার কোড (Hex)", name: "hex", widget: "string" },
            { label: "ছবি আপলোড করুন", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
          ]
        }
